AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo-list-api
  
  Sample SAM Template for todo-list-api

Globals:
  Function:
    Timeout: 5

Resources:
  GetTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./todo-list.zip
      Handler: get-todo-handler
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /todo
            Method: GET
  
  PostTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./todo-list.zip
      Handler: post-todo-handler
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /todo
            Method: POST
  
  PutTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./todo-list.zip
      Handler: put-todo-handler
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /todo
            Method: PUT
            
  DeleteTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./todo-list.zip
      Handler: delete-todo-handler
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /todo
            Method: DELETE
  
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: TID
          AttributeType: S
      KeySchema:
        - 
          AttributeName: TID
          KeyType: HASH
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1